# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    

    env:
        NODE_ENV: development
        PORT: 8888  
        MONGO_USERNAME: ${{secrets.MONGO_USERNAME}} 
        MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}} 
        MONGO_HOST: ${{secrets.MONGO_HOST}} 
        MONGO_DB: ${{secrets.MONGO_DB}} 
        MONGO_PORT: ${{secrets.MONGO_PORT}} 
    
    steps:
    - uses: actions/checkout@v2
    - name: Test Backend
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: backend
      run: |
        echo "HEYYYYYYY" 
        echo $MONGO_USERNAME
        yarn       
        yarn build 
        yarn test     
